Repository Final-Project-TravelAnchor/TravelAnchor, pull requests merged in 2024-11, with the labels that each got.

#75 React 파일 설정
  travelanchor_react/.gitignore
  travelanchor_react/src/apis/AmadeusAPICalls.js
  travelanchor_react/src/components/comments/Product.js
  travelanchor_react/src/components/comments/Product.module.css
  travelanchor_react/src/components/comments/ProductReviewModal.js
  travelanchor_react/src/components/comments/ProductReviewModal.module.css
  travelanchor_react/src/components/common/Footer.js
  travelanchor_react/src/components/common/Footer.module.css
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/components/common/LoginModal.js
  travelanchor_react/src/components/common/LoginModal.module.css
  travelanchor_react/src/components/common/MyPageNavbar.js
  travelanchor_react/src/components/common/MyPageNavbar.module.css
  travelanchor_react/src/components/common/Navbar.js
  travelanchor_react/src/components/common/Navbar.module.css
  travelanchor_react/src/layouts/Layout.js
  travelanchor_react/src/layouts/Layout.module.css
  travelanchor_react/src/layouts/MyPageLayout.js
  travelanchor_react/src/layouts/MyPageLayout.module.css
  travelanchor_react/src/pages/Main.js
  travelanchor_react/src/pages/MyPage.js
  travelanchor_react/src/pages/boards/FreeBoard.js
  travelanchor_react/src/pages/features/ExchangeRate.js
  travelanchor_react/src/pages/features/Translation.js
  travelanchor_react/src/pages/features/Weather.js
  travelanchor_react/src/pages/mates/TravelMate.js
  travelanchor_react/src/pages/notice/FAQ.js
  travelanchor_react/src/pages/notice/Notice.js
  travelanchor_react/src/pages/plans/TravelPlan.js
  travelanchor_react/src/pages/reports/TravelReport.js
  travelanchor_react/src/pages/travels/Accommodation.js
  travelanchor_react/src/pages/travels/Flight.js
  travelanchor_react/src/pages/travels/TravelDestination.js
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_create_and_grant_user.sql
Labels: Settings

#76 springboot 초기 세팅
  travelanchor_rest_server/src/main/java/travelanchor_server/common/Criteria.java
  travelanchor_rest_server/src/main/java/travelanchor_server/common/PageDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/common/PagingResponseDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/common/ResponseDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/BeanConfiguration.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/JpaConfiguration.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/JwtSecurityConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/SecurityConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/SwaggerConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/TravelanchorRestServerApplication.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/WebConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/exception/ApiExceptionAdvice.java
  travelanchor_rest_server/src/main/java/travelanchor_server/exception/DuplicatedMemberEmailException.java
  travelanchor_rest_server/src/main/java/travelanchor_server/exception/LoginFailedException.java
  travelanchor_rest_server/src/main/java/travelanchor_server/exception/TokenException.java
  travelanchor_rest_server/src/main/java/travelanchor_server/exception/dto/ApiExceptionDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/jwt/JwtAccessDeniedHandler.java
  travelanchor_rest_server/src/main/java/travelanchor_server/jwt/JwtAuthenticationEntryPoint.java
  travelanchor_rest_server/src/main/java/travelanchor_server/jwt/JwtFilter.java
  travelanchor_rest_server/src/main/java/travelanchor_server/jwt/TokenProvider.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/AuthController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/MemberController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/AuthorityDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/MemberDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/MemberRoleDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/TokenDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Authority.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Member.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/MemberRole.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/MemberRolePk.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/MemberRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/MemberRoleRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/AuthService.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/CustomUserDetailsService.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/MemberService.java
Labels: Settings

#77 sql문 더미데이터 추가
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: Settings

#78 Main Page 추가
  travelanchor_react/package.json
  travelanchor_react/src/App.js
  travelanchor_react/src/Store.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/index.js
  travelanchor_react/src/layouts/Layout.js
  travelanchor_react/src/modules/MemberModule.js
  travelanchor_react/src/modules/index.js
  travelanchor_react/src/pages/Main.js
Labels: Settings

#83 JWT, Security, sql문 테이블 추가 및 회원 정보 수정
  travelanchor_rest_server/src/main/java/travelanchor_server/config/JwtSecurityConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/SecurityConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/jwt/JwtFilter.java
  travelanchor_rest_server/src/main/java/travelanchor_server/jwt/TokenProvider.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/AuthorityDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/MemberDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/MemberRoleDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/TokenDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Authority.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Member.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/MemberRole.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/MemberRolePk.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/CustomUserDetailsService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#82 # build : 빌드 스크립트 수정(국가,도시) # 김지은
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: Settings

#84 로그인 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/AuthController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/MemberController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/MemberRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/MemberRoleRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/AuthService.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/CustomUserDetailsService.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/MemberService.java
Labels: New Feature

#85 Back 여행메이트 공고 수정 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/population/controller/PopulationController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/dto/PopulationDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/service/PopulationService.java
Labels: New Feature

#87 여행메이트 공고 추가(생성) 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/population/controller/PopulationController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/service/PopulationService.java
Labels: New Feature

#89 여행메이트 공고 상세조회 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/population/controller/PopulationController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/entity/PopulationAndCategory.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/service/PopulationService.java
Labels: New Feature

#90 # feat : 여행 후기 조회 기능
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/MapAPICalls.js
  travelanchor_react/src/pages/reports/Report.js
  travelanchor_react/src/pages/reports/TravelReport.js
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/controller/TravelReportController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/dto/TravelReportDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/entity/TravelReport.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/repository/TravelReportRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/service/TravelReportService.java
Labels: New Feature

#92 ReviewController 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/ReviewsController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/ReviewDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Review.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/ReviewRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/ReviewService.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/api/population.http
  travelanchor_rest_server/src/main/java/travelanchor_server/population/controller/PopulationController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/service/PopulationService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#93 회원후기 추가 기능 수정 및 sql문 수정
  travelanchor_rest_server/src/main/java/travelanchor_server/config/SecurityConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/api/population.http
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: Refactor

#96 아이디 찾기 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/AuthController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/MemberRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/AuthService.java
Labels: New Feature

#97 회원후기 수정 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/ReviewsController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/ReviewService.java
Labels: New Feature

#98 회원신고 추가(생성) 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/DeclareController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/DeclareDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Declare.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/DeclareRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/DeclareService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#99 여행 일정 조회 기능
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/ActivityDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/ExpenseDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/ExpenseDetailDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/TravelDayDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/TravelPlanDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/Activity.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/Expense.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/ExpenseDetail.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/TravelDay.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/TravelPlan.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/TravelPlanRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/controller/TravelReportController.java
Labels: New Feature

#100 모집공고 삭제 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/population/controller/PopulationController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/repository/PopulationRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/service/PopulationService.java
Labels: New Feature

#102 회원후기 모두 가져오기
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/ReviewsController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/ReviewRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/ReviewService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#103 # feat: 날씨예보조회기능 추가 # 김지은
  travelanchor_react/src/App.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/pages/features/Weather.js
Labels: New Feature

#105 user정보조회 및 db수정(profile_photo컬럼추가)
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/MemberController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/MemberDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Member.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/MemberService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#106 여행 일정 추가 기능
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/TravelPlanDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/TravelPlan.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#107 Feat/update user profile
  travelanchor_react/src/apis/Main.js
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/MemberController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/MemberService.java
Labels: New Feature

#108 React PopulationList 응답확인
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/PopulationAPICalls.js
  travelanchor_react/src/components/items/Population.js
  travelanchor_react/src/components/items/PopulationDetail.js
  travelanchor_react/src/components/items/PopulationList.js
  travelanchor_react/src/components/items/PopulationList.module.css
Labels: New Feature

#109 여행 일정 수정 기능
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
Labels: New Feature

#110 맛집 저장 기능 구현
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/controller/RestaurantController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/dto/RestaurantDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/entity/Restaurant.java
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/repository/RestaurantRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/service/RestaurantService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#111 항공권 가격 조회 기능
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/AmadeusAPICalls.js
  travelanchor_react/src/components/common/Header.js
Labels: New Feature

#112 비밀번호 찾기 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/config/SecurityConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/AuthController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/AuthService.java
Labels: New Feature

#113 AmadeusAPI 추가
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/AmadeusAPICalls.js
  travelanchor_react/src/apis/AmadeusFlightAPICalls.js
  travelanchor_react/src/pages/travels/Flight.js
  travelanchor_react/src/pages/travels/Flight.module.css
Labels: New Feature, Refactor, Settings

#115 AmadeusHotelAPI
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/AmadeusHotelsAPICalls.js
  travelanchor_react/src/pages/travels/Accommodation.js
Labels: New Feature, Refactor

#117 sql 회원별 권한 더미 데이터 추가
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: Settings

#118 저장된 맛집 회원별 조회 기능 구현
  travelanchor_react/src/apis/RestaurantAPICalls.js
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/MemberRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/controller/RestaurantController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/repository/RestaurantRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/service/RestaurantService.java
Labels: New Feature

#119 항공권 최저가 검색 기능 수정
  travelanchor_react/src/apis/AmadeusFlightAPICalls.js
  travelanchor_react/src/pages/travels/Flight.js
  travelanchor_react/src/pages/travels/Flight.module.css
Labels: New Feature

#120 React 모집공고 수정 기능 추가
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/PopulationAPICalls.js
  travelanchor_react/src/components/items/PopulationDetail.js
  travelanchor_react/src/components/items/PopulationModify.js
  travelanchor_react/src/modules/PopulationModule.js
Labels: New Feature

#121 활동금액 전체조회,상세조회
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/MemberController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/ExpenseRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
Labels: New Feature

#122 저장한 맛집 삭제 기능 구현
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/controller/RestaurantController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/repository/RestaurantRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/service/RestaurantService.java
Labels: New Feature

#123 활동금액/세부활동금액 전체조회 및 상세조회 가능
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/ExpenseDetailRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
Labels: New Feature

#124 SQL문 테이블 이름 변경
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: Refactor

#125 날씨 조회 기능 수정
  travelanchor_react/src/apis/WeatherAPICalls.js
  travelanchor_react/src/pages/features/Weather.js
Labels: New Feature

#126 여행 일정 삭제 기능
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/TravelPlanDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/Activity.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/TravelPlan.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/ActivityRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/ExpenseDetailRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/ExpenseRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/TravelDayRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/TravelPlanRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#127 활동금액/세부활동금액 insert가능
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/ExpenseDetailDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#128 여행지 저장 기능 구현
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/controller/RestaurantController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/entity/Restaurant.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/controller/TravelDestinationController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/dto/TravelDestinationDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/entity/TravelDestination.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/repository/TravelDestinationRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/service/TravelDestinationService.java
Labels: New Feature

#130 Front Create Population 기능 추가
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/PopulationAPICalls.js
  travelanchor_react/src/components/items/Population.js
  travelanchor_react/src/components/items/PopulationCreate.js
  travelanchor_react/src/modules/PopulationModule.js
Labels: New Feature

#131 저장한 여행지 조회 기능 구현
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/controller/TravelDestinationController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/repository/TravelDestinationRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/service/TravelDestinationService.java
Labels: New Feature

#132 국가조회 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/area/controller/CountryController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/area/dto/CountryDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/area/entity/Country.java
  travelanchor_rest_server/src/main/java/travelanchor_server/area/repository/CountryRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/area/service/CountryService.java
Labels: New Feature

#133 일반 로그인 완료 및 카카오 로그인 구현중
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/MemberAPICalls.js
  travelanchor_react/src/assets/kakao_login.png
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/pages/member/Login.js
  travelanchor_react/src/pages/member/Login.module.css
  travelanchor_react/src/utils/tokenUtils.js
  travelanchor_rest_server/src/main/java/travelanchor_server/config/SecurityConfig.java
Labels: New Feature

#135 활동금액,세부활동금액 수정 가능 / 메인css수정
  travelanchor_react/public/images/main/BtnHamberger.png
  travelanchor_react/public/images/main/TravelAnchor_image.png
  travelanchor_react/public/images/main/logo.png
  travelanchor_react/public/images/main/main_bg.png
  travelanchor_react/src/components/common/Footer.js
  travelanchor_react/src/components/common/Footer.module.css
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/components/common/common.module.css
  travelanchor_react/src/layouts/Layout.module.css
  travelanchor_react/src/pages/Main.js
  travelanchor_react/src/pages/Main.module.css
  travelanchor_react/src/pages/travels/Accommodation.js
  travelanchor_react/src/pages/travels/Flight.js
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
Labels: New Feature

#136 카카오 로그인 기능 추가
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/pages/member/Login.js
Labels: New Feature

#137 저장한 여행지 삭제 기능 구현
  travelanchor_rest_server/src/main/java/travelanchor_server/restaurant/controller/RestaurantController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/controller/TravelDestinationController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/repository/TravelDestinationRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelDestination/service/TravelDestinationService.java
Labels: New Feature

#138 항공사 코드 조회
  travelanchor_react/src/apis/AmadeusFlightAPICalls.js
  travelanchor_react/src/pages/travels/Flight.js
Labels: New Feature

#139 여행 일정, 후기, 자유게시판 crud
  travelanchor_rest_server/src/main/java/travelanchor_server/freeboard/controller/FreeBoardController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/freeboard/dto/FreeBoardDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/freeboard/entity/FreeBoard.java
  travelanchor_rest_server/src/main/java/travelanchor_server/freeboard/repository/FreeBoardRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/freeboard/service/FreeBoardService.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/controller/TravelReportController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/dto/TravelReportDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/entity/TravelReport.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/service/TravelReportService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#140 활동금액,세부활동금액 삭제
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/Expense.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
Labels: New Feature

#141 PointReward DB TBL 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/PointController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/PointDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Point.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/PointRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/PointService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#142 텍스트 번역 기능 추가 및 페이지 수정
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/TranslationAPICalls.js
  travelanchor_react/src/components/common/Footer.js
  travelanchor_react/src/components/common/Footer.module.css
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/pages/features/Translation.css
  travelanchor_react/src/pages/features/Translation.js
Labels: New Feature

#143 댓글 조회, 등록, 수정, 삭제 기능 추가
  travelanchor_rest_server/src/main/java/travelanchor_server/comment/controller/CommentController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/comment/dto/CommentDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/comment/entity/Comment.java
  travelanchor_rest_server/src/main/java/travelanchor_server/comment/repository/CommentRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/comment/service/CommentService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#144 1/N 정산을 위한 세부활동금액조회 수정
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/ExpenseDetailRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#145 드롭다운 외 자잘한 수정
  travelanchor_react/src/assets/fonts/NanumGothicBold.ttf
  travelanchor_react/src/components/common/Footer.module.css
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/index.css
  travelanchor_react/src/layouts/Layout.js
  travelanchor_react/src/layouts/Layout.module.css
  travelanchor_react/src/pages/Main.module.css
  travelanchor_react/src/pages/features/Translation.css
Labels: New Feature

#146 Chat기능 추가
  travelanchor_react/package-lock.json
  travelanchor_react/package.json
  travelanchor_react/src/App.js
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_react/src/components/items/PopulationDetail.js
  travelanchor_rest_server/build.gradle
  travelanchor_rest_server/src/main/java/travelanchor_server/common/ChatMessage.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/ChattingConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/SecurityConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/ChatController.java
Labels: New Feature

#148 공고마다 채팅방의 메세지 격리
  travelanchor_react/package-lock.json
  travelanchor_react/package.json
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_rest_server/src/main/java/travelanchor_server/common/ChatMessage.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/ChatController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Message.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/MessageRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/MessageService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#149 환율 조회
  travelanchor_react/package.json
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/ExchangeRateAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/pages/features/ExchangeRate.css
  travelanchor_react/src/pages/features/ExchangeRate.js
Labels: New Feature

#152 환율 계산기
  travelanchor_react/src/apis/ExchangeRateAPICalls.js
  travelanchor_react/src/pages/features/ExchangeRate.css
  travelanchor_react/src/pages/features/ExchangeRate.js
Labels: New Feature

#153 공지사항 기능 추가
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/NoticeAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/modules/NoticeModule.js
  travelanchor_react/src/modules/index.js
  travelanchor_react/src/pages/notice/Notice.js
  travelanchor_react/src/pages/notice/NoticeCreate.js
  travelanchor_react/src/pages/notice/NoticeDetail.js
  travelanchor_react/src/pages/notice/NoticeList.js
  travelanchor_react/src/pages/notice/NoticeList.module.css
  travelanchor_react/src/pages/notice/NoticeModify.js
  travelanchor_rest_server/src/main/java/travelanchor_server/population/controller/NoticeController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/dto/NoticeDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/entity/Notice.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/repository/NoticeRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/service/NoticeService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature, Refactor

#156 세부활동금액 전체조회,상세조회 가능
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/ExpenseAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/common.module.css
  travelanchor_react/src/modules/ExpenseDetailModule.js
  travelanchor_react/src/modules/index.js
  travelanchor_react/src/pages/plans/ExpenseInsert.js
  travelanchor_react/src/pages/plans/ExpenseList.js
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/ExpenseDetailRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
Labels: New Feature

#157 맛집 전체 조회 기능 구현 완료
  travelanchor_react/package-lock.json
  travelanchor_react/package.json
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/RestaurantAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/modules/RestaurantModule.js
  travelanchor_react/src/pages/restaurants/Restaurants.js
  travelanchor_react/src/pages/restaurants/Restaurants.module.css
  travelanchor_react/src/server/server.js
Labels: Refactor

#158 실시간 채팅 기능 수정.
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_rest_server/src/main/java/travelanchor_server/freeboard/controller/FreeBoardController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/freeboard/service/FreeBoardService.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/MessageService.java
Labels: Refactor

#159 맛집 전체 조회 기능 수정
  travelanchor_react/src/pages/restaurants/Restaurants.js
  travelanchor_react/src/pages/restaurants/Restaurants.module.css
  travelanchor_react/src/server/server.js
Labels: Refactor

#160 도시 조회
  travelanchor_react/src/apis/AreaAPICalls.js
  travelanchor_react/src/modules/AreaModule.js
  travelanchor_react/src/modules/index.js
  travelanchor_react/src/pages/travels/Flight.js
Labels: New Feature

#161 헤더오류 수정
  travelanchor_react/src/components/common/Header.js
Labels: Refactor

#162 세부활동금액 추가 가능
  travelanchor_react/src/App.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/pages/plans/ExpenseInsert.js
  travelanchor_react/src/pages/plans/ExpenseList.js
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#164 맛집 조회 기능 구현 수정
  travelanchor_react/server/server.js
  travelanchor_react/src/apis/RestaurantAPICalls.js
Labels: Refactor

#165 server.js 코드 수정
  travelanchor_react/server/server.js
Labels: Refactor

#166 세부활동금액 수정가능
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/ExpenseAPICalls.js
  travelanchor_react/src/pages/plans/ExpenseList.js
  travelanchor_react/src/pages/plans/ExpenseUpdate.js
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
Labels: New Feature

#168 회원가입 기능 추가 및 수정
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/MemberAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/pages/Main.js
  travelanchor_react/src/pages/member/Register.js
  travelanchor_react/src/pages/member/Register.module.css
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/AuthService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature, Refactor

#167 항공권 조회 오류 및 css 수정
  travelanchor_react/src/apis/AmadeusFlightAPICalls.js
  travelanchor_react/src/pages/travels/Flight.css
  travelanchor_react/src/pages/travels/Flight.js
  travelanchor_react/src/pages/travels/Flight.module.css
Labels: Refactor

#169 아이디 찾기 기능 추가
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/MemberAPICalls.js
  travelanchor_react/src/pages/member/FindId.js
  travelanchor_react/src/pages/member/FindId.module.css
  travelanchor_react/src/pages/member/Login.js
Labels: New Feature

#170 세부활동금액 삭제가능
  travelanchor_react/src/apis/ExpenseAPICalls.js
  travelanchor_react/src/modules/ExpenseDetailModule.js
  travelanchor_react/src/pages/plans/ExpenseList.js
Labels: New Feature

#171 후기 작성을 위한 Redux추가.
  travelanchor_react/package-lock.json
  travelanchor_react/package.json
  travelanchor_react/src/Store.js
  travelanchor_react/src/modules/PlanModule.js
  travelanchor_react/src/modules/index.js
  travelanchor_react/src/pages/reports/AddReportDate.js
  travelanchor_react/src/pages/reports/AddReportDestination.js
  travelanchor_react/src/pages/reports/TravelReport.js
Labels: Refactor, Settings

#172 공지사항 css 추가
  travelanchor_react/src/pages/notice/Notice.css
  travelanchor_react/src/pages/notice/Notice.js
  travelanchor_react/src/pages/notice/NoticeCreate.css
  travelanchor_react/src/pages/notice/NoticeCreate.js
  travelanchor_react/src/pages/notice/NoticeDetail.css
  travelanchor_react/src/pages/notice/NoticeDetail.js
  travelanchor_react/src/pages/notice/NoticeList.css
  travelanchor_react/src/pages/notice/NoticeList.js
  travelanchor_react/src/pages/notice/NoticeModify.css
  travelanchor_react/src/pages/notice/NoticeModify.js
Labels: style

#173 비밀번호 찾기 기능 추가
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/MemberAPICalls.js
  travelanchor_react/src/pages/member/FindId.js
  travelanchor_react/src/pages/member/FindPw.js
  travelanchor_react/src/pages/member/FindPw.module.css
  travelanchor_react/src/pages/member/Login.js
  travelanchor_react/src/pages/member/Login.module.css
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/AuthController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/AuthService.java
Labels: New Feature

#175 공지사항 스타일 추가 및 변경
  travelanchor_react/src/pages/notice/Notice.css
  travelanchor_react/src/pages/notice/Notice.js
  travelanchor_react/src/pages/notice/NoticeCreate.css
  travelanchor_react/src/pages/notice/NoticeCreate.js
  travelanchor_react/src/pages/notice/NoticeDetail.css
  travelanchor_react/src/pages/notice/NoticeDetail.js
  travelanchor_react/src/pages/notice/NoticeList.js
  travelanchor_react/src/pages/notice/NoticeList.module.css
  travelanchor_react/src/pages/notice/NoticeModify.css
  travelanchor_react/src/pages/notice/NoticeModify.js
Labels: style

#176 실시간채팅 사진전송 기능 추가
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_rest_server/src/main/java/travelanchor_server/config/ChattingConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/config/SecurityConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/ChatController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/ChatMessageDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Message.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/MessageService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#177 날씨 조회 css 추가
  travelanchor_react/src/pages/features/Weather.css
  travelanchor_react/src/pages/features/Weather.js
Labels: style

#178 맛집 상세조회 기능 구현
  travelanchor_react/server/server.js
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/RestaurantAPICalls.js
  travelanchor_react/src/pages/restaurants/RestaurantDetail.js
  travelanchor_react/src/pages/restaurants/Restaurants.js
Labels: New Feature

#180 채팅룸 css 수정
  travelanchor_react/src/components/items/ChatRoom.css
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_rest_server/src/main/resources/static/orange-1117645_1280.jpg
Labels: style

#182 여행지 전체 조회 기능 구현
  travelanchor_react/server/server.js
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/TravelDestinationAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/pages/travels/TravelDestination.js
  travelanchor_react/src/pages/travels/TravelDestination.module.css
  travelanchor_react/src/pages/travels/TravelDestinations.js
Labels: New Feature

#183 여행 후기 등록 기능 완료
  travelanchor_react/src/modules/CityModule.js
  travelanchor_react/src/modules/index.js
  travelanchor_react/src/pages/reports/AddReportDestination.js
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/dto/TravelReportDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/entity/TravelReport.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/service/TravelReportService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#184 회원, 비회원에 따른 로직 추가
  travelanchor_react/src/apis/NoticeAPICalls.js
  travelanchor_react/src/apis/PopulationAPICalls.js
  travelanchor_react/src/components/items/Population.js
  travelanchor_react/src/components/items/PopulationDetail.js
  travelanchor_react/src/modules/MemberModule.js
  travelanchor_react/src/pages/boards/FreeBoard.js
  travelanchor_react/src/pages/boards/FreeBoardCreate.js
  travelanchor_react/src/pages/boards/FreeBoardDetail.js
  travelanchor_react/src/pages/notice/Notice.js
  travelanchor_react/src/pages/notice/NoticeDetail.js
  travelanchor_react/src/pages/reports/TravelReport.js
  travelanchor_react/src/utils/tokenUtils.js
  travelanchor_rest_server/src/main/java/travelanchor_server/population/controller/NoticeController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/service/NoticeService.java
Labels: New Feature, Refactor

#185 로그인 후 마이페이지 조회가능
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/MemberAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/modules/MemberModule.js
  travelanchor_react/src/pages/MyPage.js
  travelanchor_react/src/pages/member/Login.js
  travelanchor_react/src/pages/member/MyPage.js
  travelanchor_react/src/pages/member/MyPage.module.css
Labels: New Feature

#186 메이트 관련 페이지 css 추가 및 수정
  travelanchor_react/src/components/common/common.module.css
  travelanchor_react/src/components/items/ChatRoom.css
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_react/src/components/items/Population.css
  travelanchor_react/src/components/items/Population.js
  travelanchor_react/src/components/items/PopulationCreate.css
  travelanchor_react/src/components/items/PopulationCreate.js
  travelanchor_react/src/components/items/PopulationDetail.css
  travelanchor_react/src/components/items/PopulationDetail.js
  travelanchor_react/src/components/items/PopulationModify.css
  travelanchor_react/src/components/items/PopulationModify.js
  travelanchor_rest_server/src/main/resources/static/hot-air-balloon.jpg
  travelanchor_rest_server/src/main/resources/static/orange-1117645_1280.jpg
Labels: style

#187 도시 조회 오류 수정
  travelanchor_react/src/pages/travels/Flight.js
Labels: Refactor

#188 사용자가 만든 게시글의 수정버튼 로직
  travelanchor_react/src/components/items/PopulationDetail.js
  travelanchor_react/src/pages/boards/FreeBoardDetail.js
  travelanchor_react/src/utils/tokenUtils.js
Labels: New Feature, Refactor

#189 여행지 상세 조회 기능 구현
  travelanchor_react/server/server.js
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/RestaurantAPICalls.js
  travelanchor_react/src/apis/TravelDestinationAPICalls.js
  travelanchor_react/src/pages/restaurants/RestaurantDetail.js
  travelanchor_react/src/pages/travels/TravelDestinationDetail.js
  travelanchor_react/src/pages/travels/TravelDestinationDetail.module.css
  travelanchor_react/src/pages/travels/TravelDestinations.js
Labels: New Feature

#190 실시간 채팅 이름나오게 추가
  travelanchor_react/src/Store.js
  travelanchor_react/src/apis/FreeBoardAPICalls.js
  travelanchor_react/src/apis/MemberAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_react/src/components/items/PopulationDetail.js
  travelanchor_react/src/pages/boards/FreeBoardList.js
  travelanchor_react/src/pages/member/Login.js
  travelanchor_react/src/pages/notice/Notice.js
  travelanchor_react/src/utils/tokenUtils.js
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/ChatMessageDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Message.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: Refactor

#191 실시간 채팅 시 사진 전송
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/ChatController.java
Labels: Refactor

#192 채팅방 간단프로필 기능 추가
  travelanchor_react/src/components/items/ChatRoom.css
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_react/src/components/items/ProfilePopup.js
Labels: New Feature, Refactor

#193 자유게시판 수정
  travelanchor_react/src/pages/boards/FreeBoardModify.js
Labels: Refactor

#194 회원정보수정기능 작성중(미완성 커밋)
  travelanchor_react/src/App.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/components/common/common.module.css
  travelanchor_react/src/pages/member/MyPage.js
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/MemberController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/MemberService.java
  travelanchor_rest_server/src/main/resources/static/TravelAnchorLogo.png
  travelanchor_rest_server/src/main/resources/static/hot-air-balloon.jpg
Labels: New Feature

#195 회원정보수정기능 작성중(미완성 커밋)
  travelanchor_react/src/apis/MemberAPICalls.js
  travelanchor_react/src/pages/member/MyPageUpdate.js
  travelanchor_react/src/pages/member/MyPageUpdate.module.css
Labels: New Feature

#196 자유게시판 css 및 자잘한 수정
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/TranslationAPICalls.js
  travelanchor_react/src/pages/boards/FreeBoard.css
  travelanchor_react/src/pages/boards/FreeBoard.js
  travelanchor_react/src/pages/boards/FreeBoardDetail.css
  travelanchor_react/src/pages/boards/FreeBoardDetail.js
  travelanchor_react/src/pages/boards/FreeBoardList.js
  travelanchor_react/src/pages/features/Translation.css
  travelanchor_react/src/pages/features/Translation.js
Labels: style

#197 sql 인덱스 추가 및 더미 수정/ 회원가입 기능 추가
  travelanchor_react/public/index.html
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/MemberAPICalls.js
  travelanchor_react/src/pages/member/Register.js
  travelanchor_react/src/pages/member/Register.module.css
  travelanchor_rest_server/src/main/java/travelanchor_server/member/dto/MemberDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/entity/Member.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/repository/MemberRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/AuthService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature, Refactor

#198 유저프로필 사진업로드 및 수정 기능 작성중(미완성커밋)
  travelanchor_react/public/images/main/default-avatar.png
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/MemberAPICalls.js
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/modules/MemberModule.js
  travelanchor_react/src/pages/Main.module.css
  travelanchor_react/src/pages/member/MyPage.js
  travelanchor_react/src/pages/member/MyPageUpdate.js
  travelanchor_react/src/pages/member/MyPageUpdate.module.css
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/FileUploadController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/MemberController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/MemberService.java
Labels: New Feature

#199 여행지 저장 front 구현 중
  travelanchor_react/server/server.js
  travelanchor_react/src/apis/FavoriteTravelDestinationCalls.js
  travelanchor_react/src/apis/TravelDestinationAPICalls.js
  travelanchor_react/src/modules/FavoriteTravelDestinationModule.js
  travelanchor_react/src/pages/travels/TravelDestinationDetail.js
Labels: New Feature

#200 후기 CRUD
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/TravelReportAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/pages/reports/AddReportDestination.js
  travelanchor_react/src/pages/reports/TravelReport.js
  travelanchor_react/src/pages/reports/TravelReportCreate.js
  travelanchor_react/src/pages/reports/TravelReportCreateForm.js
  travelanchor_react/src/pages/reports/TravelReportDetail.js
  travelanchor_react/src/pages/reports/TravelReportList.js
  travelanchor_react/src/pages/reports/TravelReportModify.css
  travelanchor_react/src/pages/reports/TravelReportModify.js
  travelanchor_rest_server/.env
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/TravelPlanDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/TravelPlan.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/controller/TravelReportController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/dto/TravelReportDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/entity/TravelReport.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/service/TravelReportService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#201 공지사항 수정 후 전체목록으로 이동 로직 변경
  travelanchor_react/src/components/items/PopulationDetail.js
  travelanchor_react/src/pages/boards/FreeBoardDetail.js
  travelanchor_react/src/pages/notice/NoticeModify.js
Labels: Refactor

#202 여행일정 CRUD 구현
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/TravelPlanAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/modules/TravelPlanModule.js
  travelanchor_react/src/modules/index.js
  travelanchor_react/src/pages/plans/AddPlanDate.js
  travelanchor_react/src/pages/plans/AddPlanDestination.js
  travelanchor_react/src/pages/plans/TravelPlan.css
  travelanchor_react/src/pages/plans/TravelPlan.js
  travelanchor_react/src/pages/plans/TravelPlanCreate.js
  travelanchor_react/src/pages/plans/TravelPlanDetail.js
  travelanchor_react/src/pages/plans/TravelPlanList.js
  travelanchor_react/src/pages/plans/TravelPlanUpdate.css
  travelanchor_react/src/pages/plans/TravelPlanUpdate.js
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/TravelPlan.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#203 메이트 공지 조회수 기능 추가
  travelanchor_react/src/components/items/PopulationCreate.js
  travelanchor_react/src/components/items/PopulationDetail.js
  travelanchor_rest_server/src/main/java/travelanchor_server/config/SecurityConfig.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/controller/PopulationController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/population/service/PopulationService.java
Labels: Refactor

#204 외래키 충돌문제 -> 전부 주석처리.
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: Settings

#205 FreeBoard 관련, 자잘한 style
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/components/common/common.module.css
  travelanchor_react/src/pages/boards/FreeBoard.css
  travelanchor_react/src/pages/boards/FreeBoardCreate.css
  travelanchor_react/src/pages/boards/FreeBoardCreate.js
  travelanchor_react/src/pages/boards/FreeBoardDetail.css
  travelanchor_react/src/pages/boards/FreeBoardDetail.js
  travelanchor_react/src/pages/boards/FreeBoardList.js
  travelanchor_react/src/pages/boards/FreeBoardModify.css
  travelanchor_react/src/pages/boards/FreeBoardModify.js
  travelanchor_react/src/pages/features/ExchangeRate.css
  travelanchor_react/src/pages/features/Translation.css
  travelanchor_react/src/pages/features/Weather.css
  travelanchor_react/src/pages/travels/Flight.css
  travelanchor_react/src/pages/travels/Flight.js
Labels: style

#207 구글 로그인 기능 추가 및 css 적용
  travelanchor_react/package-lock.json
  travelanchor_react/package.json
  travelanchor_react/src/App.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/index.js
  travelanchor_react/src/modules/MemberModule.js
  travelanchor_react/src/pages/member/GoogleLogin.js
  travelanchor_react/src/pages/member/GoogleLoginComponent.module.css
  travelanchor_react/src/pages/member/Login.js
  travelanchor_react/src/pages/member/Login.module.css
  travelanchor_rest_server/src/main/java/travelanchor_server/jwt/TokenProvider.java
Labels: New Feature

#208 Accommodation 기능 정리 및 스타일 추가
  travelanchor_react/src/apis/AmadeusHotelsAPICalls.js
  travelanchor_react/src/pages/travels/Accommodation.css
  travelanchor_react/src/pages/travels/Accommodation.js
  travelanchor_react/src/pages/travels/Accommodation.module.css
Labels: Refactor, style

#209 마이페이지 수정중
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/pages/member/MyPage.js
  travelanchor_react/src/pages/member/MyPage.module.css
  travelanchor_react/src/pages/member/MyPageUpdate.js
  travelanchor_react/src/pages/member/MyPageUpdate.module.css
  travelanchor_rest_server/src/main/resources/static.uploadedImages/default-avatar.png
Labels: New Feature

#210 로그인 버튼 css 수정
  travelanchor_react/src/pages/member/Login.js
  travelanchor_react/src/pages/member/Login.module.css
Labels: style

#212 아이디 찾기 기능 수정 및 css 추가
  travelanchor_react/public/images/main/lock.png
  travelanchor_react/src/pages/member/FindId.js
  travelanchor_react/src/pages/member/FindId.module.css
Labels: style

#213 비밀번호 찾기 기능 수정 및 css 추가
  travelanchor_react/src/pages/member/FindId.js
  travelanchor_react/src/pages/member/FindPw.js
  travelanchor_react/src/pages/member/FindPw.module.css
  travelanchor_rest_server/src/main/java/travelanchor_server/member/controller/AuthController.java
Labels: style

#214 후기 보완, 날짜 하루씩 당겨지는 부분
  travelanchor_react/src/App.js
  travelanchor_react/src/pages/reports/AddReportDate.js
  travelanchor_react/src/pages/reports/AddReportDestination.js
  travelanchor_react/src/pages/reports/TravelReport.js
  travelanchor_react/src/pages/reports/TravelReportCreate.js
  travelanchor_react/src/pages/reports/TravelReportDetail.js
  travelanchor_react/src/pages/reports/TravelReportModify.js
Labels: New Feature

#215 자유게시판 내 댓글 기능
  travelanchor_react/src/apis/CommentAPICalls.js
  travelanchor_react/src/modules/CommentModule.js
  travelanchor_react/src/modules/index.js
  travelanchor_react/src/pages/boards/FreeBoardDetail.css
  travelanchor_react/src/pages/boards/FreeBoardDetail.js
  travelanchor_rest_server/src/main/java/travelanchor_server/comment/dto/CommentDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/comment/entity/Comment.java
  travelanchor_rest_server/src/main/java/travelanchor_server/comment/service/CommentService.java
Labels: New Feature, style

#216 헤더, 새로고침, 햄버거 로그인 풀림 해결
  travelanchor_react/src/App.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/pages/member/Register.js
Labels: Refactor

#217 마이페이지 나의 후기 조회 기능 추가
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/TravelReportAPICalls.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/modules/TravelReportModule.js
  travelanchor_react/src/pages/reports/TravelReportByMember.js
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/controller/TravelReportController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/repository/TravelReportRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelreport/service/TravelReportService.java
Labels: New Feature

#219 일정 세부 작성 전 일부 푸시
  travelanchor_react/src/App.js
  travelanchor_react/src/apis/ActivityAPICalls.js
  travelanchor_react/src/apis/TravelPlanAPICalls.js
  travelanchor_react/src/modules/ActivityModule.js
  travelanchor_react/src/modules/PlanModule.js
  travelanchor_react/src/modules/TravelPlanModule.js
  travelanchor_react/src/modules/index.js
  travelanchor_react/src/pages/plans/ActivityList.js
  travelanchor_react/src/pages/plans/ActivityUpdate.js
  travelanchor_react/src/pages/plans/AddByDayPlan.js
  travelanchor_react/src/pages/plans/DayPlanDetail.js
  travelanchor_react/src/pages/plans/TravelPlan.js
  travelanchor_react/src/pages/plans/TravelPlanCreate.js
  travelanchor_react/src/pages/plans/TravelPlanDetail.js
  travelanchor_react/src/pages/plans/TravelPlanList.js
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/TravelDayDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/TravelDay.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/ActivityRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/TravelDayRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/TravelPlanRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: Refactor

#220 마이페이지 정보조회,수정 페이지 자잘한 수정
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/Header.module.css
  travelanchor_react/src/pages/member/MyPage.js
  travelanchor_react/src/pages/member/MyPage.module.css
  travelanchor_react/src/pages/member/MyPageUpdate.js
  travelanchor_react/src/pages/member/MyPageUpdate.module.css
  travelanchor_rest_server/src/main/java/travelanchor_server/member/service/MemberService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: New Feature

#221 맛집 스타일 수정
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/pages/restaurants/RestaurantDetail.js
  travelanchor_react/src/pages/restaurants/RestaurantDetail.module.css
  travelanchor_react/src/pages/restaurants/Restaurants.js
  travelanchor_react/src/pages/restaurants/Restaurants.module.css
  travelanchor_react/src/pages/travels/LandmarkDetail.module.css
Labels: style

#223 sql 더미데이터 추가
  travelanchor_react/src/App.js
  travelanchor_react/src/components/common/UnderConstruction.js
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
  travelanchor_rest_server/src/main/resources/static/hot-air-balloon.jpg
Labels: Refactor

#224 세부일정 로직, 채팅창 날짜 로직
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/common/UnderConstruction.js
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_react/src/modules/index.js
  travelanchor_react/src/pages/plans/TravelPlanDetail.js
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/controller/TravelPlanController.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/dto/ExpenseDTO.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/entity/Expense.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/repository/ExpenseRepository.java
  travelanchor_rest_server/src/main/java/travelanchor_server/travelplan/service/TravelPlanService.java
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: Refactor

#225 사진 추가
  travelanchor_react/src/apis/ExpenseAPICalls.js
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_react/src/modules/ExpenseDetailModule.js
  travelanchor_react/src/pages/plans/TravelPlanDetail.js
  travelanchor_rest_server/src/main/resources/static.uploadedImages/hot-air-balloon.jpg
  travelanchor_rest_server/src/main/resources/static/hot-air-balloon.jpg
Labels: Settings

#226 css 추가 및 수정
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_react/src/components/items/PopulationList.js
  travelanchor_react/src/components/items/PopulationList.module.css
  travelanchor_react/src/pages/travels/Accommodation.js
  travelanchor_rest_server/src/main/resources/static/exchange.png
  travelanchor_rest_server/src/main/resources/static/translation.png
  travelanchor_rest_server/src/main/resources/static/weather.png
Labels: style

#227 햄버거 문제 해결
  travelanchor_react/package-lock.json
  travelanchor_react/package.json
  travelanchor_react/src/components/common/Header.js
Labels: Refactor

#228 후기 css
  travelanchor_react/src/App.js
  travelanchor_react/src/components/common/Header.js
  travelanchor_react/src/pages/reports/AddReportDate.js
  travelanchor_react/src/pages/reports/AddReportDestination.js
  travelanchor_react/src/pages/reports/TravelReport.js
  travelanchor_react/src/pages/reports/TravelReportCreate.js
  travelanchor_react/src/pages/reports/TravelReportDetail.js
  travelanchor_react/src/pages/reports/TravelReportList.js
  travelanchor_rest_server/src/main/resources/sql/TravelAnchorDB_build_script.sql
Labels: style

#229 후기 css 추가
  travelanchor_react/src/pages/reports/AddReportDate.css
  travelanchor_react/src/pages/reports/AddReportDestination.css
  travelanchor_react/src/pages/reports/TravelReport.css
  travelanchor_react/src/pages/reports/TravelReportCreate.css
  travelanchor_react/src/pages/reports/TravelReportDetail.css
  travelanchor_react/src/pages/reports/TravelReportList.css
Labels: style

#230 여행지, 랜드마크 자잘한 css 수정
  travelanchor_react/src/pages/travels/LandmarkDetail.module.css
  travelanchor_react/src/pages/travels/TravelDestination.module.css
  travelanchor_react/src/pages/travels/TravelDestinationDetail.js
  travelanchor_react/src/pages/travels/TravelDestinationDetail.module.css
  travelanchor_react/src/pages/travels/TravelDestinations.js
Labels: style

#231 여행지 저장 기능 구현하는 중
  travelanchor_react/src/apis/FavoriteTravelDestinationCalls.js
  travelanchor_react/src/pages/travels/SavedTravelDestination.js
  travelanchor_react/src/pages/travels/TravelDestinationDetail.js
Labels: Refactor

#232 회원가입 css 수정
  travelanchor_react/src/pages/member/Register.js
  travelanchor_react/src/pages/member/Register.module.css
Labels: style

#236 채팅방 스타일 수정, 헤더 아이콘 변경
  travelanchor_react/src/components/items/ChatRoom.css
  travelanchor_react/src/components/items/ChatRoom.js
  travelanchor_rest_server/src/main/resources/static/weather.png
Labels: style

#237 여행지 자잘한 css 수정
  travelanchor_react/src/pages/travels/LandmarkDetail.js
  travelanchor_react/src/pages/travels/LandmarkDetail.module.css
  travelanchor_react/src/pages/travels/TravelDestination.module.css
  travelanchor_react/src/pages/travels/TravelDestinationDetail.js
  travelanchor_react/src/pages/travels/TravelDestinationDetail.module.css
  travelanchor_react/src/pages/travels/TravelDestinations.js
Labels: style

#238 마이페이지 정보수정페이지 css
  travelanchor_react/src/pages/member/MyPageUpdate.js
  travelanchor_react/src/pages/member/MyPageUpdate.module.css
Labels: style

#239 환율, 나의여행후기 css 추가
  travelanchor_react/src/pages/features/ExchangeRate.css
  travelanchor_react/src/pages/features/ExchangeRate.js
  travelanchor_react/src/pages/reports/TravelReportByMember.css
  travelanchor_react/src/pages/reports/TravelReportByMember.js
Labels: style
